<?php

/**
 * @file
 * Module hooks and alters for Admin UI customizations.
 */

use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function sitestudio_gin_preprocess_page(&$variables) {
  // Global CSS overrides.
  $variables['#attached']['library'][] = 'sitestudio_gin/sitestudio_gin-global-overrides';

  // Overrides only if Gin is the active theme,
  // or a base theme of the active theme.
  if (_is_gin_or_gin_subtheme()) {
    $variables['#attached']['library'][] = 'sitestudio_gin/sitestudio_gin-gin-overrides';

    $route = \Drupal::routeMatch()->getRouteName();
    if ($route == 'sitestudio-page-builder.layout_canvas.frontend_edit_component'
      && !empty($variables['page']['gin_secondary_toolbar'])) {
      // Remove the gin secondary toolbar from the Site Studio iframe.
      unset($variables['page']['gin_secondary_toolbar']);
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\cohesion_elements\Form\ComponentContentForm.
 *
 * Changes vertical tabs to container.
 *
 * Note: Adapted from cohesion_elements_form_component_content_edit_form_alter()
 * for gin admin theme.
 *
 * @see cohesion_elements_form_component_content_edit_form_alter()
 * @see claro_form_node_form_alter()
 */
function sitestudio_gin_form_component_content_edit_form_alter(&$form, FormStateInterface $form_state) {
  if (_is_gin_or_gin_subtheme()) {
    $form['#theme'] = ['node_edit_form'];
    $form['#attached']['library'][] = 'claro/node-form';

    $form['advanced']['#type'] = 'container';
    $form['advanced']['#accordion'] = TRUE;
    $form['meta']['#type'] = 'container';
    $form['meta']['#access'] = TRUE;
    $form['meta']['changed']['#wrapper_attributes']['class'][] = 'container-inline';
    $form['meta']['author']['#wrapper_attributes']['class'][] = 'container-inline';

    $form['revision_information']['#type'] = 'container';
    $form['revision_information']['#group'] = 'meta';
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \ Drupal\cohesion_elements\Form\ComponentContentForm.
 *
 * Changes vertical tabs to container.
 *
 * Note: Adapted from cohesion_elements_form_component_content_edit_form_alter()
 * for gin admin theme.
 *
 * @see sitestudio_gin_form_component_content_edit_form_alter()
 */
function sitestudio_gin_form_component_content_add_form_alter(&$form, FormStateInterface $form_state) {
  sitestudio_gin_form_component_content_edit_form_alter($form, $form_state);
}

/**
 * Implements hook_gin_content_form_routes().
 *
 * Register routes to apply the Gin content edit form layout.
 */
function sitestudio_gin_gin_content_form_routes() {
  return [
    // Layout a component content using node form.
    'entity.component_content.add_form',
    'entity.component_content.canonical',
    'entity.component_content.edit_form',
  ];
}

/**
 * Helper function to check if Gin or a child theme of Gin is active.
 */
function _is_gin_or_gin_subtheme() {
  $active_theme = \Drupal::theme()->getActiveTheme();
  $theme_keys = array_keys($active_theme->getBaseThemeExtensions());
  $theme_keys[] = $active_theme->getName();

  if (in_array('gin', $theme_keys)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Implements hook_form_alter().
 *
 * @todo: Remove this when the Site Studio issue this is needed for is resolved.
 * @see: https://www.drupal.org/project/sitestudio_gin/issues/3358530
 */
function sitestudio_gin_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if ($form_state->getFormObject() instanceof EntityFormInterface
    && $form_state->getFormObject()->getEntity() instanceof FieldableEntityInterface) {
    $entity = $form_state->getFormObject()->getEntity();
    // Check that there is a Layout canvas field on the entity.
    foreach ($entity->getFieldDefinitions() as $field) {
      if ($field->getType() == 'cohesion_entity_reference_revisions') {
        // If there is a layout canvas field, add a fake submit button to the form.
        $form['sitestudio_gin_fake_submit'] = [
          '#type' => 'submit',
          '#value' => t('Submit'),
          '#disabled' => TRUE,
          '#attributes' => [
            'style' => 'display: none;'
          ],
        ];
        return;
      }
    }
  }
}
